modLoader="javafml"
loaderVersion="[43,)"
license="All Rights Reserved"

[[mods]]
modId="mapsyncer"
version="1.0.1"
displayName="MapSyncer"
description="Syncs server-side explored areas to client's Xaero World Map"
authors="Ruo_Chen"

[[dependencies.mapsyncer]]
modId="neoforge"
type="required"
versionRange="[43,)"
ordering="NONE"
side="BOTH"

[[dependencies.mapsyncer]]
modId="minecraft"
type="required"
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"